---
name: pull-request

on:
  pull_request:
    branches: [main, test, dev]

jobs:
  yaml:
    name: yaml code validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Linting
        run: yamllint .

  terraform:
    name: terraform code validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'

      - name: install tfsec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Install precommit and run
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit
